repository_type: pipeline

nf_core_version: 3.3.1

lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: nf-core
  name: t2pmhc_benchmark
  description: A unified pipeline for running and comparing diverse machine learning
    tools to predict T cell-antigen interactions.
  author: Mark Polster
  version: 0.0.1dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  is_nfcore: true
